content:
- name: cases
  label: Cases
  type: collection
  format: json
  path: "src/content/cases"
  filename: "{fields.slug}.{fields.lang}.json"
  fields:
  - name: slug
    label: Slug
    description: Always include '/' in the slug. 'deutzkrueger.de/slug'
    type: string

  - name: lang
    label: Language
    type: select
    options:
      values: [ { value: en, label: English }, { value: de, label: German } ]

  - name: client
    label: Client Name
    type: string

  - name: groups
    label: Block Groups
    type: block
    list: true
    blocks:
    - name: group
      label: Group
      fields:
      - name: group_title
        description: This title is just for organisation. It won't be visible on the site.
        label: Group Title
        type: string
      - name: blocks
        label: Blocks
        type: block
        list: true
        blocks:
        - name: title
          component: title
        - name: image
          component: image
        - name: video
          component: video
        - name: text
          component: text

  - name: case_preview
    label: Preview shown on the landing page
    type: object
    fields:
    - name: title
      label: Preview Title
      type: text
    - name: preview_image
      label: Preview Image
      component: image_component

- name: landing_page
  label: Landing Page
  type: collection
  format: json
  path: "src/content/pages/landing-page"
  filename: "{fields.lang}.json"
  view:
    primary: hero.headline
    fields: [ lang, hero.headline ]
  fields:
  - name: lang
    label: Language
    type: select
    options:
      values: [ { value: en, label: English }, { value: de, label: German } ]

  - name: hero
    label: Hero Section
    type: object
    fields:
    - { name: headline, type: text, label: Headline }

  - name: cases
    label: Cases
    type: reference
    options:
      collection: "cases"
    list:
      collapsible:
        collapsed: false
        summary: "{title}"
      max: 5

  - name: services
    label: Services
    type: object
    list:
      max: 3
      collapsible:
        collapsed: false
        summary: "{fields.title}"
    fields:
    - name: title
      label: Service Title
      type: string
    - name: body
      label: Service Description
      type: text
    - name: icon
      label: Service Icon
      type: object
      fields:
      - name: iconLogo
        label: Logo for Icon
        component: image
      - name: iconColor
        label: Icon Color
        description: The color as a hex value. eg. "#425E6B"
        type: string

- name: about_page
  label: About Page
  type: collection
  format: json
  filename: "{fields.lang}.json"
  path: "src/content/pages/about"
  view:
    fields: [ lang, headline ]
    primary: headline
  fields:
  - name: lang
    label: Language
    type: select
    options:
      values: [ { value: en, label: English }, { value: de, label: German } ]
  - { name: headline, type: text, label: Headline }
  - { name: body, type: text, label: Body }

- name: layout
  label: Layout Settings
  type: file
  path: "src/content/settings/layout.json"
  format: json
  fields:
  - name: navItems
    label: Navigation Links
    type: object
    list:
      collapsible:
        collapsed: false
        summary: "{fields.title} | {fields.href}"
    fields:
    - name: href
      label: URL ending
      description: Always include '/' in the slug. 'deutzkrueger.de/slug'
      type: string
    - name: title
      label: Displayed text
      type: string

  - name: footerItems
    label: Footer Links
    type: object
    list:
      collapsible:
        collapsed: false
        summary: "{fields.title} | {fields.href}"
    fields:
    - name: href
      label: URL ending
      description: "Always include / in the slug. 'deutzkrueger.de/slug'"
      type: string
    - name: title
      label: Displayed text
      type: string
  - name: logo
    label: Header Logo
    component: image

- name: settings
  label: Site Settings
  type: file
  path: "src/content/settings/settings.json"
  format: json
  fields:
  - name: title
    label: Website title
    type: string
  - name: description
    label: Website description
    type: string
    description: Will be used for any page with no description.
  - name: url
    label: Website URL
    type: string
    pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
  - name: cover
    label: Preview image
    component: image
    description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: legal
    label: Legal Stuff
    description: Stuff like privacy policy, Impressum, etc.
    type: object
    fields:
    - name: impressum
      label: Impressum
      type: object
      fields:
      - name: title
        label: Impressum Title
        type: string
      - name: body
        label: Impressum Body
        type: text
    - name: privacy
      label: Privacy Policy
      description: Add the Privacy Policy as a PDF.
      type: object
      fields:
      - name: title
        label: Privacy Policy Title
        type: string
      - name: body
        label: PP body as PDF
        type: file
        options:
          media: files
          categories: [ document ]

components:
  background:
    label: Background Settings
    description: |
      All settings used to set the background of images and videos.
      If a background is wanted choose either static or animated.
      Static: A solid color. If there is more than 1 color provided, the background will always be the first color
      Animated: Based on the provided colors a gradient will be generated which animates.
    type: object
    fields:
    - name: background
      label: Background Type
      type: select
      options:
        values:
        - value: none
          label: None
        - value: static
          label: Static Background
        - value: gradient
          label: Gradient Background
    - name: backgroundColors
      label: Background Color(s)
      description: "The # must be included per color. #EBEBEB is the default color."
      type: string
      default: "#EBEBEB"
      list:
        collapsible: false

  layout:
    label: Block Layout
    type: object
    fields:
    - name: width
      label: Block Width
      type: select
      values: [ { value: 1 }, { value: 2 }, { value: 3 }, { value: 4 } ]
    - name: position
      label: Starting Column
      type: select
      values: [ { value: 1 }, { value: 2 }, { value: 3 }, { value: 4 } ]

  base:
    type: object
    label: Base settings
    fields:
    - name: background
      component: background
    - name: layout
      component: layout

  video:
    label: Video Block
    type: object
    fields:
    - name: video
      label: Video File
      type: file
      options:
        categories: [ video ]
    - name: base
      component: base

  image:
    label: Image Block
    type: object
    fields:
    - name: image
      label: Image File
      component: image_component
    - name: base
      component: base

  text:
    label: Text Block
    type: object
    fields:
    - name: text
      label: Text
      type: text
    - name: base
      component: base

  title:
    label: Case Title
    type: object
    fields:
    - name: title
      label: Case Title
      type: string
    - name: subHeading
      label: Case Subheading
      type: text
    - name: base
      component: base

  image_component:
    label: Image File
    type: object
    fields:
    - name: src
      label: Image File
      type: file
      options:
        categories: [ image ]
    - name: alt
      label: Alt Text
      type: string

media:
- name: media
  label: Media
  input: src/content/media
  output: /src/content/media
  extensions: [ png, webp, jpg, jpeg, svg, mp4, mov, webm ]
- name: files
  label: Files & Documents
  input: public/documents
  output: /documents
  categories: [ document ]
