allowBuilds:
  esbuild: true
  ffmpeg-static: true
  sharp: true
  swup: true
  workerd: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild
  - ffmpeg-static
  - sharp
  - swup
  - workerd

publicHoistPattern:
  - linkedoms
