name: Build

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    environment: CLOUDFLARE
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"
      - run: pnpm install

      - name: "Create .env file"
        run: |
          touch .env
          echo CLOUDFLARE_ACCOUNT_ID=${{ vars.CLOUDFLARE_ACCOUNT_ID }} >> .env
          echo CLOUDFLARE_MEDIA_API_TOKEN=${{ secrets.CLOUDFLARE_MEDIA_API_TOKEN }} >> .env
          cat .env

      - name: Cache media-sync manifest
        id: cache-manifest
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-sync-${{ hashFiles('./src/content/media/**') }}
          path: |
            ./media-sync/manifest.json

      - name: Sync media files
        run: pnpm sync-media

      - name: Build project
        run: pnpm run build
